# Generated by Django 6.0.1 on 2026-01-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greeting', models.CharField(default="Hello, I'm Aiza Dawood", max_length=100)),
                ('main_title', models.CharField(default='CRAFTING DIGITAL EXPERIENCES', max_length=200)),
                ('sub_text', models.TextField()),
            ],
        ),
    ]
