# Generated by Django 6.0.1 on 2026-01-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('tech', 'Technical'), ('prof', 'Professional')], default='tech', max_length=10),
        ),
    ]
